name: Docker Build

on:
  push:
    branches:
      - main # Change this to your main branch name, e.g., master

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image for the frontend
        run: cd frontend && docker build -t frontend:latest .

  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image for the backend
        run: cd backend && docker build -t backend:latest .

      # Optional: You can push the built image to a Docker registry
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Push Docker image
      #   run: docker push your_image_name:latest
